### ISSUE TITLE
Usability: add button to expand/collapse neighborhood list

### ISSUE THREAD

**Issue by ajRiverav** [Code4PuertoRico/suministrospr#103]
The problem is that in the mobile version there's a lot of scrolling to get to neighborhoods at the very end. As the list grows, the problem is exacerbated.

I suggest a signifier is added (e.g. a button, most likely) to provide the user the affordance of  expanding and collapsing the neighborhood list. This results in an easier, faster navigation experience.

**Comment by ajRiverav** [comment]
visualized: 

![image](https://user-images.githubusercontent.com/22076301/72641246-a5734180-3937-11ea-88b1-c7fc9fdef692.png)

**Comment by gcollazo** [comment]
Se ve bien pero hay que hold los cambios de UI hasta que #77 lands. Se decidió hacer un rewrite del CSS para eliminar la dependencia de tailwind.

**Comment by arrel** [comment]
I took a shot at this today, opening a PR now. This was just an easy one I picked off to try to contribute something. It's a little hard to tell what's already in progress so let me know if there are other issues (front-end or back) that would be good to work on without duplicating work. Thx!

**Comment by froi** [comment]
Closing this issue since it was solved in PR #148
