### ISSUE TITLE
Add Search

### ISSUE THREAD

**Issue by miguelrios** [Code4PuertoRico/suministrospr#105]
Tags are cool, pero mucho mejor sería añadir funcionalidad de search para q la gente pueda buscar cosas específicas como "agua", "casetas", "medicina", etc. Podemos usar tags para algunas de esas pero una solución más general bregaría mejor a largo plazo.

**Comment by miguelrios** [comment]
This describes a potential quick solution: https://stackoverflow.com/questions/2584502/simple-search-in-django

**Comment by miguelrios** [comment]
Or if we're using postgres https://docs.djangoproject.com/en/3.0/ref/contrib/postgres/search/

**Comment by gcollazo** [comment]
@jpadilla lo q hicimos en tesoro?

**Comment by froi** [comment]
We can use a similar model to what @jpadilla and I are doing in contratospr.

**Comment by froi** [comment]
Hey peeps.

Acabo de darle push a lo mas reciente para la busqueda. Esta en el PR #117 

Necesito un poco de ayuda con el UI. Feel free to edit the PR directly or submit a PR to the search branch.
