### ISSUE TITLE
refactor UX for barrio screen

### ISSUE THREAD

**Issue by ajRiverav** [Code4PuertoRico/suministrospr#108]
Not sure where the team is designing things (e.g. in a slack group or somewhere)...but I propose this: 

![image](https://user-images.githubusercontent.com/22076301/72642625-d0ab6000-393a-11ea-9f28-0dc15581cff3.png)

- Did a few usability tests and they passed. 
- It also helps with the flow of needs -> en route -> delivered, and the duplicity of deliveries that arise because the wiki does not provide a "state" for each suministro.

Pardon the orthographical errors.

**Comment by ajRiverav** [comment]
if they team can provide what they have in mind to coordinate entregas, this can be adjusted.

**Comment by gcollazo** [comment]
Sugiero hold los cambios de UI hasta que #77 lands

**Comment by ajRiverav** [comment]
aj: maybe close this. Acabo de ver https://github.com/Code4PuertoRico/suministrospr/issues/11, que era lo que estaba buscando para entender actual requirements de la calle.
