### ISSUE TITLE
Publicar viajes de entrega de suministros

### ISSUE THREAD

**Issue by gcollazo** [Code4PuertoRico/suministrospr#11]
Las personas que harán viajes para entregar suministros deben poder publicar:

- Cuando van a hacer el viaje
- A donde van a ir a llevar suministros
- Que suministros van a llevar en ese viaje
- Info de contacto para que quien quiera aportar suministros a ese viaje pueda entregarlos 
- Modificar home para mostrar:
  - Necesidades por refugio (esto es la data que ya tenemos)
  - Entregas de suministros (la data que producirá este feature)

![Desktop HD](https://user-images.githubusercontent.com/61048/72385879-c0a33e80-36f6-11ea-9dc1-8dea4b131c40.png)

### Puntos de integración
- Botón en home [Crear entrega de suministros] - lleva a formulario para crear entrega
- Botón en pagina de refugio [Crear entrega de suministros] - lleva a formulario para crear entrega con lugar de entrega pre-seleccionado pero editable.

### Campos de formulario
- Nombre de grupo o persona encargado de la entrega
- Teléfono
- Otra info de contacto
- Fecha de salida de viaje de entrega de suministros
- Lugar de entrega
- Descripción - campo abierto con algunas sugerencias de que texto incluir como placeholder o en un help text.
  - ¿Se estarán aceptando suministros del público? ¿Hasta cuando? ¿Lugar de encuentro?
  - ¿Que suministros se llevarán?
  - ¿Necesitan vehículos adicionales?
  - ¿La entrega fue completada?
  - Enlaces a fotos en social media de la entrega

### Página de entregas / Lista de entregas en home
- Organizada por fecha de entrega (la próxima primero)
- Esconder entregas que haya pasado la fecha con filtro (Ver entregas anteriores)

### Stretch goals
- En campo de lugar de entrega poder seleccionar de la lista de lugares registrados o crear lugar con solo entrar nombre
- Marcar entrega como completada

**Comment by ajRiverav** [comment]
esto se va a añadir para v2 o #77 tiene que ver con esto? 

Sé que quieren aguantar UI proposals hasta que se haga #77, pero tengo wireframes refactoring esto. La idea es poder ver qué se va a implementar (antes de que se haga) para en lugar proponer breaking changes, que sean enhancements.

**Comment by ajRiverav** [comment]
Acá el refactoring (mobile-first) para q se piense. Resuelve mucha de las ambiguedades del sketch de arriba. Todos los requirements arriba (e.g. puntos de integración, etc...) aplican. 

![image](https://user-images.githubusercontent.com/22076301/72665966-81693c00-39db-11ea-8ba2-ef2ecdfb79d1.png)

![image](https://user-images.githubusercontent.com/22076301/72666058-8bd80580-39dc-11ea-8cb1-b1daca090d87.png)

![image](https://user-images.githubusercontent.com/22076301/72666076-b45fff80-39dc-11ea-933c-12dd2f1bc1d7.png)


![image](https://user-images.githubusercontent.com/22076301/72666035-4b788780-39dc-11ea-8bfe-ffe7f1aebb9c.png)

**Comment by LaysCurbelo** [comment]
Saludos @gcollazo 

Aqui mi sugerencia para el merge de ambos request:

Es básicamente añadir en la area del viaje que tipo de voluntario estará en ese viaje y añadir incluso cuanto se pronostica durara el recurso que estan entregando así si veo que se hizo una entrega de insulina por ejemplo y los voluntarios comentarón la entrega debe durar 5 dias de consumo para 20 pacientes si veo la fecha cuando se publico y el tiempo de consumo se cuando yo puedo ir a la misma zona para repetir esa donación. 

Quedo atenta para seguir ayudando! Vamos a darle!!

![Suministrosprv2](https://user-images.githubusercontent.com/60011942/72683458-edb47000-3aad-11ea-910a-bf2d4f72bf98.png)
[Suministrosprv2.pdf](https://github.com/Code4PuertoRico/suministrospr/files/4082839/Suministrosprv2.pdf)

**Comment by froi** [comment]
Hola @gcollazo 

¿Cual es el estado de este issue? ¿Se esta trabajando?
