### ISSUE TITLE
Cache form queries

### ISSUE THREAD

**Issue by jpadilla** [Code4PuertoRico/suministrospr#111]
We're currently not doing response caching for create/update form view because CSRF tokens. We should still be able to cache queries. These must be invalidated accordingly.

<img width="1114" alt="Screen Shot 2020-01-18 at 1 41 54 PM" src="https://user-images.githubusercontent.com/83319/72668846-ea12e180-39f8-11ea-857c-27d846cc48c2.png">

**Comment by jpadilla** [comment]
@rnegron is assigned to work on this.

**Comment by jpadilla** [comment]
@rnegron heads up, I moved cache invalidation to signals here https://github.com/Code4PuertoRico/suministrospr/pull/132. Whatever else we cache, we should invalidate there when needed.

**Comment by froi** [comment]
@jpadilla @rnegron any updates on this issue? Marking as stale for the moment. Please remove the label if this is not the case.
