### ISSUE TITLE
Sección de Voluntarios

### ISSUE THREAD

**Issue by LaysCurbelo** [Code4PuertoRico/suministrospr#113]
Debería añadirse una sección donde se puedan registrar voluntarios especificos. Entiendase por personas con habilidades especializadas que deseen donar su tiempo. No es lo mismo un grupo de voluntarios generales que un grupo de voluntarios enfermeros. Asi se pueden movilizar los suministros con voluntarios especificos para areas con mayor urgencia (como ancianos con necesidades especiales). 

Adjunto un User Flow de lo que pudiese ser esta sección en la página, soy UX si necesitan ayuda cuenten conmigo. 

![Suministrospr](https://user-images.githubusercontent.com/60011942/72669124-9b6b4480-3a04-11ea-9598-c74ef4bbb1c5.png)
[Suministrospr.pdf](https://github.com/Code4PuertoRico/suministrospr/files/4081524/Suministrospr.pdf)

**Comment by LaysCurbelo** [comment]
A ustedes! Lo que necesiten me dejan saber, pueden contactarme tambien por aqui layscurbelo@gmail.com

**Comment by froi** [comment]
@gcollazo creo que esto es pa’ ti.

**Comment by gcollazo** [comment]
@LaysCurbelo Estamos trabajando en una solución más general que serviría para resolver este mismo de problema con #11.

El caso que traes es no lo teníamos presente porque nadie en el campo nos ha dicho que es un problema. Dicho eso creo que está suficientemente cerca como para que podamos acomodar el caso dentro de lo que estamos trabajando.

Mi sugerencia sería replantear este feature dentro de lo que plantea #11. ¿Cuál es el número mínimo de cambios posibles a #11 para que se pueda resolver lo que planteas?

Para poder ejecutar rápido debemos hacer "trade offs" la primera versión de la solución no será perfecta pero debe posibilitar el caso de uso. Más adelante podemos desarrollar un feature específico e ideal.

Te invito a entrar a #11 y sugerir el mínimo número de cambios posible para lograr habilitar este caso. Creo que estos cerca.

**Comment by LaysCurbelo** [comment]
Hice mi comentario en #11, no obstante lo adjunto aqui igualmente. Gracias @gcollazo !!
![Suministrosprv2](https://user-images.githubusercontent.com/60011942/72686403-aab4c580-3aca-11ea-80c5-9eeeef8a0523.png)
[Uploading Suministrosprv2.pdf…]()
