### ISSUE TITLE
Community requirement - Add an Open Source license

### ISSUE THREAD

**Issue by froi** [Code4PuertoRico/suministrospr#119]
Siendo un repo dentro de Code 4 Puerto Rico tenemos que añadir una licencia Open Source al proyecto.

@gcollazo Siendo el stakeholder del proyecto te dejo a ti y al equipo original de suministrospr la decision de que licencia utilizar.

**Comment by froi** [comment]
Friendly ping @gcollazo 😄

**Comment by gcollazo** [comment]
Pienso que debemos usar [Apache 2](https://www.apache.org/licenses/LICENSE-2.0.html) pero estoy súper open a considerar otra cosa.

**Comment by froi** [comment]
I agree with that. Do you want me to do a PR for you or do you want to do it?

**Comment by gcollazo** [comment]
@froi please do

**Comment by froi** [comment]
Esto se resolvio con el PR #149
