### ISSUE TITLE
Request for API

### ISSUE THREAD

**Issue by JesusAlvelo** [Code4PuertoRico/suministrospr#127]
Hola, sería interesante que hubiera un API para poder visualizar y cuantificar los suministros por regiones/pueblo. Esto ayudaría a coordinar y repartí suministros de forma eficiente y evitar redundancias. Gracias por su labor.

**Comment by gcollazo** [comment]
Hola @JesusAlvelo sin duda esto es algo que queremos tener. Por el momento estamos enfocados en entregar features directamente en el site. Es la forma más rápida y ahora (en medio de la emergencia) debemos optimizar para eso.

Si te interesa trabajar en este feature déjanos saber y podemos hablar para compartir nuestra visión de como atacar este problema.

**Comment by JesusAlvelo** [comment]
@gcollazo zumba Yandel. Seguro, dime como puedo ayudar. Nunca he trabajado con features pero le meto mano

**Comment by gcollazo** [comment]
@JesusAlvelo lo más útil y rápido sería un read-only API. 

Si duda queremos usar Django Rest Framework. Como no tienes experiencia según dices te diría que le dedicara un tiempo y hagas un PR con tu progreso para
pedir support. Este feature es low priority en este momento

**Comment by JesusAlvelo** [comment]
No hay problema!
