### ISSUE TITLE
Link GitHub repo on footer

### ISSUE THREAD

**Issue by gcollazo** [Code4PuertoRico/suministrospr#136]
Creo que debemos linkiar el archivo CONTRIBUTING de este repo, en el footer del site con un texto que diga algo como "¿Como ayudar?"

@Xiomara7 @froi ¿Qué creen?

**Comment by froi** [comment]
Me gusta esa idea.

**Comment by Xiomara7** [comment]
A mi también. Yo puedo hacerlo.

**Comment by Xiomara7** [comment]
¿Algo así? 

<img width="926" alt="Screen Shot 2020-01-19 at 11 33 16 PM" src="https://user-images.githubusercontent.com/3449724/72696855-2424d600-3b14-11ea-904a-c632a3583e37.png">

**Comment by gcollazo** [comment]
Gracias @Xiomara7 

Creo que así se vería mejor y ayuda a separar el footer completo del content.

![Slice](https://user-images.githubusercontent.com/61048/72730546-fb2e3080-3b67-11ea-94e5-ed5b88dcda41.png)
