### ISSUE TITLE
Sectores en la página del municipio no concuerdan con los desplegados en la página principal

### ISSUE THREAD

**Issue by albertico** [Code4PuertoRico/suministrospr#137]
Mientras añadía categorías para el municipio de Jayuya me percaté que la lista de sectores en la página principal no concuerda con la lista de sectores en la página del municipio de Jayuya.

A continuación se muestra la página principal de [SuministrosPR.com](https://suministrospr.com) con los sectores de Jayuya:

![suministrospr-jayuya-main-page](https://user-images.githubusercontent.com/1066016/72692446-f9c61f00-3af9-11ea-9818-c3441e6d5572.jpg)

Al presionar sobre "Jayuya" la aplicación te lleva a la página que desplega los sectores de dicho municipio. Los sectores desplegados en la página de Jayuya no concuerdan con la página principal:

![suministrospr-jayuya-bug-not-rendering-all-sectores](https://user-images.githubusercontent.com/1066016/72692495-43166e80-3afa-11ea-89a8-56102f1f7b86.jpg)

Al revisar en el `admin` se puede confirmar que existen 8 entradas para el municipio de Jayuya que concuerdan con las desplegadas en la página principal:

![suministrospr-jayuya-admin-sectores](https://user-images.githubusercontent.com/1066016/72692654-20388a00-3afb-11ea-9de4-122a817f1795.jpg)

**Comment by albertico** [comment]
El mismo problema sucede con Adjuntas.

Página principal con sectores de Adjuntas (10 sectores):

![suministrospr-adjuntas-main-page](https://user-images.githubusercontent.com/1066016/72695762-ac50ae80-3b07-11ea-93a6-e6931671263b.jpg)

Página del municipio de Adjuntas (8 sectores solamente):

![suministrospr-adjuntas-bug-not-rendering-all-sectores](https://user-images.githubusercontent.com/1066016/72695776-c4283280-3b07-11ea-9acd-f7c5a201a1ff.jpg)

Sectores para el municipio de Adjuntas en el `admin` (10 sectores):

![suministrospr-adjuntas-admin-sectores](https://user-images.githubusercontent.com/1066016/72695843-0b162800-3b08-11ea-8eb6-e05947900ef8.jpg)

**Comment by jpadilla** [comment]
Investigando.

**Comment by jpadilla** [comment]
Creo que esto es caching inconsistencies tbh. Pienso que #132 fixes this issue. Will confirm later today.

**Comment by albertico** [comment]
Probably. Sorry, I didn't test any further (I was adding tags to as many posts as possible). If you can't replicate the problem locally using the same data, I would agree with the caching. It's probably not worth putting too much energy into this issue until #132 gets deployed.

**Comment by albertico** [comment]
Also, do people visit the actual "municipio" page? Would be nice for someone to take a look at the analytics. cc: @gcollazo

**Comment by gcollazo** [comment]
![top-pages](https://user-images.githubusercontent.com/61048/72749259-efeefb00-3b8f-11ea-9a79-25eed0464355.png)

**Comment by froi** [comment]
@albertico @jpadilla @gcollazo 

Este issue todavía es valido?
