### ISSUE TITLE
Asignar Categorías: Lajas

### ISSUE THREAD

**Issue by albertico** [Code4PuertoRico/suministrospr#138]
## Lajas

- [x] Cancha Lluch y parking de manejo de emergencias
- [ ] Club de Leones - Lajas
- [x] Colinas de La Parguera (Calle 3, Solar 39)
- [x] Coliseo Juan Lluch
- [x] Cuesta Blanca
- [x] Healthy Body Factory
- [x] Barrio Paris
- [x] Lajas Encarnación
- [x] Los Hornos

**Comment by albertico** [comment]
Review:

- [ ] Posible Duplicado:
  - Cancha Lluch y Parking de Manejo de Emergencias: https://suministrospr.com/sectores/cancha-lluch-y-parking-de-manejo-de-emergencias/
  - Coliseo Juan Lluch: https://suministrospr.com/sectores/coliseo-juan-lluch/
- [ ] Este "post" parece más una organización preguntando quién necesita ayuda en vez de un sector solicitando ayuda (Unclear how to proceed):
  - Club de Leones - Lajas: https://suministrospr.com/sectores/club-de-leones-lajas-lajas/

**Comment by albertico** [comment]
Considerándolo completado por ahora.

**Comment by froi** [comment]
Esto se debería cerrar o estamos esperando ese ultimo checkbox?

**Comment by gcollazo** [comment]
Closing si alguien más reporta algo reabrimos
