### ISSUE TITLE
Añadir nombre del municipio al breadcrumb

### ISSUE THREAD

**Issue by jwvelez** [Code4PuertoRico/suministrospr#144]
Esto estaba funcionando bien antes pero ya no están saliendo los Municipios en el breadcrumb.
![Screenshot 2020-01-20 13 57 35](https://user-images.githubusercontent.com/10341619/72748200-f334b780-3b8c-11ea-88c8-7d93e7084318.png)

**Comment by jonatns** [comment]
I'll give it a try!

**Comment by albertico** [comment]
Gracias por crear este issue @jwvelez. Me percaté del mismo problema mientras añadía "tags" a los sectores.

**Comment by jpadilla** [comment]
Gracias @jonatns! Closed via #145
