### ISSUE TITLE
Terms of service y Privacy policy

### ISSUE THREAD

**Issue by gcollazo** [Code4PuertoRico/suministrospr#147]
Ya tenemos alguien trabajando esto. Creo issue para keep track.

**Comment by dalcalapr** [comment]
[TOS - suministrospr.docx](https://github.com/Code4PuertoRico/suministrospr/files/4120490/TOS.-.suministrospr.docx)

**Comment by dalcalapr** [comment]
Adjunto los Terminos de Uso. Deben verificarlo, y le falta unos links a ciertas licencias (entre otros). Se basa en el TOS de Wikipidea. Manana les envio los Privacy Policy.

**Comment by gcollazo** [comment]
Gracias @dalcalapr

**Comment by froi** [comment]
@gcollazo Any updates with this?

- Should we move forward with the TOS that was submitted?
- Should we create our own Privacy Policy?

**Comment by dalcalapr** [comment]
Sorry, no había escuchado más de esto, puedo hacer los Privacy policy esta semana.

**Comment by froi** [comment]
Relax @dalcalapr y gracias. Solo quería estar seguro que no dejemos nada en el limbo 😄
