### ISSUE TITLE
Details page is not rendering links

### ISSUE THREAD

**Issue by froi** [Code4PuertoRico/suministrospr#28]
The details page is not rendering links at all. All text with an anchor tag is being escaped. These links are showing correctly in in the edit page for an entry.

Example, the detail for entry with `bo-bucarabones-maricao` slug:

<img width="878" alt="details-missing-links" src="https://user-images.githubusercontent.com/1918027/72322208-2bfbfa80-367c-11ea-8826-04ea0621b460.png">

**Comment by jpadilla** [comment]
Per https://github.com/Code4PuertoRico/suministrospr/issues/4#issuecomment-574189804, we need to add some basic styling for markup generated by the editor.

**Comment by jpadilla** [comment]
@froi this should be fixed now.

> This url is not a in the content itself.

En el source https://suministrospr.com/sectores/bo-bucarabones-2/ no tiene un `<a>`.

**Comment by gcollazo** [comment]
Agree con que el site actual tiene links así que no necesitamos links por ahora... Closing
