### ISSUE TITLE
Añadir campo de localización a refugios y puntos de encuentro para entregas de suministros

### ISSUE THREAD

**Issue by malopezcruz** [Code4PuertoRico/suministrospr#31]
¿Se podría, de alguna manera, sistematizar en el editor o alguna otra parte del UI la entrada de las coordenadas de la comunidad? Esto facilitaría la llegada de los recursos. Tomo como ejemplo la aplicación sos-sur de gcollazo.

**Comment by gcollazo** [comment]
@malopezcruz de acuerdo con que debemos tomar información de location al momento de crear o editar un lugar

**Comment by torlanco** [comment]
Esto es uno de los datos mas importantes, quizás añadirle un ‘verified’ ☑️
