### ISSUE TITLE
Importar datos existentes antes de deploy

### ISSUE THREAD

**Issue by gcollazo** [Code4PuertoRico/suministrospr#34]
Hay un scrapper creado como parte de #8. Antes del deploy / switch debemos hacer un último export / import.

El import process debería `get_or_create` y si existe solo update, queremos poder correr el import varias veces sin duplicar lugares pero si actualizando los datos.

Es inevitable que el cambio de DNS tarde un poco en estar en efecto en todas partes por lo que seguramente vamos a tener que update la data una vez el site nuevo esté arriba.

**Comment by jpadilla** [comment]
@froi habría que modificar el import_data management command para que sea idempotent.

**Comment by albertico** [comment]
@gcollazo Se puede reducir el TTL del DNS?

**Comment by gcollazo** [comment]
@albertico buen punto, lo acabo de bajar a 2min

**Comment by jpadilla** [comment]
Tenemos que importar los datos usando el slug original.

Ejemplo: https://suministrospr.com/sectores/barriada-ferran-sector-san-francisco/
Slug: barriada-ferran-sector-san-francisco

Usar el slug original nos va a permitir hacer el proceso de importación idempotent.

Este cambio debe de ser en el `import_data` management command.

I can work on this at 7pm. Anybody else is welcome to do so before I get back.

Luego de esto podemos coordinar hacer el primer deploy y reemplazar la herramienta original.

**Comment by froi** [comment]
@jpadilla I'm working on this
