### ISSUE TITLE
Añadir map con rutas

### ISSUE THREAD

**Issue by froi** [Code4PuertoRico/suministrospr#37]
Este pedido nos Twitter y posiblemente esta relacionado a #31.

[![image](https://user-images.githubusercontent.com/1918027/72372191-4bc30b00-36dc-11ea-81e4-89718c533bee.png)]( https://twitter.com/tercapaciencia/status/1217132247146475525)

No tenemos muchos detalles pero una vez los consigamos los añado aquí.

**Comment by gcollazo** [comment]
@froi considero este un duplicate de #31... closing
