### ISSUE TITLE
Create detail view page

### ISSUE THREAD

**Issue by jpadilla** [Code4PuertoRico/suministrospr#4]
Based on https://suministrospr.com/sectores/aguas-blancas/

**Comment by jpadilla** [comment]
Falta añadir basic styling para markup generado por el editor.

Update: Working on it

**Comment by jpadilla** [comment]
Addressed via #28

**Comment by froi** [comment]
There are some conflicts that need to be addressed and after that it should be good to go.

**Comment by froi** [comment]
@jpadilla saw your merge of #28 I'm closing this out.
