### ISSUE TITLE
AttributeError on first load of resource

### ISSUE THREAD

**Issue by tommytomtj** [Code4PuertoRico/suministrospr#48]
So I'm getting an error _"AttributeError: 'bool' object has no attribute 'get'"_ when I click on links for the first time. If i reload the page or go back and click again it works fine. I think I narrowed the issue down to the CacheMixin.

Adding a line with _response.render()_ right below the cache.set lambda seems to resolve the issue for me. I'll submit that change for you guys to determine if it makes sense.

**Comment by jpadilla** [comment]
@tommytomtj sorry about that, should be fixed in https://github.com/Code4PuertoRico/suministrospr/commit/000ae80ecb1a6974467d665cc1acb125a0085eaf
