### ISSUE TITLE
Improve styling of long titles

### ISSUE THREAD

**Issue by jpadilla** [Code4PuertoRico/suministrospr#49]
<img width="1406" alt="Screen Shot 2020-01-14 at 11 08 55 PM" src="https://user-images.githubusercontent.com/83319/72404345-fc53fd80-3722-11ea-9fe9-61ef1be67be9.png">

vs

<img width="1406" alt="Screen Shot 2020-01-14 at 11 10 28 PM" src="https://user-images.githubusercontent.com/83319/72404376-18f03580-3723-11ea-8651-006448f1f930.png">

**Comment by luisgthb** [comment]
I’ll check this one out.

**Comment by jpadilla** [comment]
Fixed via #52
