### ISSUE TITLE
Create new page

### ISSUE THREAD

**Issue by jpadilla** [Code4PuertoRico/suministrospr#5]
Based on: https://suministrospr.com/helpie_editor_page/?editor_mode=add-article

We can skip functionality to create municipalities, we can hardcode all of them.

**Comment by froi** [comment]
Current "add article" page

![image](https://user-images.githubusercontent.com/1918027/72320549-4fbd4180-3678-11ea-8f4c-e9017e68ae25.png)

Original "add article" page:

![image](https://user-images.githubusercontent.com/1918027/72320581-619ee480-3678-11ea-9cbf-a680aa0ce4cf.png)

**Comment by froi** [comment]
Adding a new article:

![image](https://user-images.githubusercontent.com/1918027/72320835-d3772e00-3678-11ea-81b7-8e0448d57ae8.png)

Validating article added:
<img width="1258" alt="suministros-add-article-validation" src="https://user-images.githubusercontent.com/1918027/72320856-dffb8680-3678-11ea-9a46-c9194051b20c.png">

**Comment by froi** [comment]
Only "issue" here is that when adding a new article the site leaves the use in the add article page.

@Code4PuertoRico/suministrospr is that a behavior that we want or do we want to send the user to the detail page of what was just added?
