### ISSUE TITLE
Some potential improvements for V2

### ISSUE THREAD

**Issue by miguelrios** [Code4PuertoRico/suministrospr#51]
Some thoughts on (near) future improvements

**On Categorization**
I think the request page needs improvements on structuring but I like the “wiki” and “free form” nature of it. I don’t know how to balance the two. 

One possible hack (which may not be sustainable depending on volume) is to have a slack hook that notifies a group of us whenever there is an update posted and we go and add “tags” or categories for each request. Then folks who want to help can search easily for “need supplies”, “need water”, “need mental health help” etc.

**broadcasting on twitter**
The slack hook could also be useful to broadcast needs more publicly. Like this: https://twitter.com/oajvelez/status/1217133605752922117?s=21. We can get alerted when new items get added and use discretion to post them publicly (I have the @puertorico account or we could use other). 

**Matching needs with “suppliers”**
I like the idea of publishing trips. We can take it beyond and have a simple for that folks use to say what they have and then match them with needs that have been identified. Having tags and categories would be key then. We can then have those folks “acknowledging” the request for help and would be published in the sector/refugio page.

**Comment by gcollazo** [comment]
Creo que #11 ataca algunos de estos puntos pero optimiza para ship it rápido. La desventaja del diseño de #11 es que no es data estructurada.

Creo que podemos lanzar de esta versión free form para tener el feature lo antes posible y en la próxima vuelta añadir más estructura y referencias cruzadas. Sin duda es con lo que queremos terminar. 

Sobre lo de tener un canal público para push posts estoy 100% de acuerdo. Prefiero usar solo Twitter y que los que quieran participar de hacer ediciones o compartir que se subscriban a push notif. o sms de la cuanta a la que se publiquen los posts. Eso llenaría ambos requisitos con un solo feature. 

Si hay muchos que quieren slack también lo pondría para la próxima ronda. 

Voy a crear issues individuales para esta conversación.

**Comment by miguelrios** [comment]
Sg. Me avisas si quieren usar @puertorico.

**Comment by miguelrios** [comment]
Y agree con optimizar para ship it rápido. Algo q puedo hacer en el bg es un simple ml model q lea el texto y lo categorize. Puede ayudar para quienes busquen como ayudar (filtrar by need_supplies por ejemplo). No tiene q ser muy complicado. Empecé a label data aquí: https://docs.google.com/spreadsheets/d/16alvWnwEu-aMD5IHiUH_NHkuNfB9oaKiWTiGMXp-jSM/edit#gid=1555248691. Voy a crear un issue para esto y pedir ayuda labeling data a ver como sale.

**Comment by gcollazo** [comment]
Eso sería espectacular! Déjame saber si necesitas algo para poder moverte adelante.

**Comment by Xiomara7** [comment]
> Y agree con optimizar para ship it rápido. Algo q puedo hacer en el bg es un simple ml model q lea el texto y lo categorize. Puede ayudar para quienes busquen como ayudar (filtrar by need_supplies por ejemplo). No tiene q ser muy complicado. Empecé a label data aquí: https://docs.google.com/spreadsheets/d/16alvWnwEu-aMD5IHiUH_NHkuNfB9oaKiWTiGMXp-jSM/edit#gid=1555248691. Voy a crear un issue para esto y pedir ayuda labeling data a ver como sale.

I can help labeling.

**Comment by gcollazo** [comment]
Cerrando ya que hay issues tracking los features que salen de esta conversación, si se quedara algo please feel free de crear issues adicionales.
