### ISSUE TITLE
Optimize rendering on small displays.

### ISSUE THREAD

**Issue by luisgthb** [Code4PuertoRico/suministrospr#53]
Some elements aren’t making the best use of the space available.

**Homepage** on mobile (iPhone X)
![0 0 0 0_8000_(iPhone X)](https://user-images.githubusercontent.com/2643495/72417635-4c44bb80-3747-11ea-8b45-ec4f90270c43.png)

**Suministros** on mobile (iPhone X)
![0 0 0 0_8000_suministros_piedras-blancas-guayanilla-2_(iPhone X)](https://user-images.githubusercontent.com/2643495/72417647-523a9c80-3747-11ea-8013-f2b07eeab8c2.png)

![0 0 0 0_8000_suministros_parking-de-bknoches-y-areas-aledanas-al-coliseo-de_(iPhone X)](https://user-images.githubusercontent.com/2643495/72417663-55ce2380-3747-11ea-8c81-70493c56c959.png)

**Comment by jpadilla** [comment]
- [ ] Smaller logo on header
- [ ] Less horizontal padding
- [ ] Larger buttons
- [ ] Smaller font size for text in header

Results from https://suministrospr.com/sectores/barrio-magueyes-alto-calle-2-al-final-guanica-p-r/

<img width="616" alt="Screen Shot 2020-01-15 at 9 26 31 AM" src="https://user-images.githubusercontent.com/83319/72441763-38b24880-3779-11ea-8af9-10d11105bf8b.png">

**Comment by jpadilla** [comment]
@luisv5z wanna take a stab at these tweaks?

**Comment by luisgthb** [comment]
@gcollazo Are you working on this one?

**Comment by gcollazo** [comment]
@luisv5z si
