### ISSUE TITLE
Status Meeting v1

### ISSUE THREAD

**Issue by gcollazo** [Code4PuertoRico/suministrospr#54]
Hagamos un video call hoy en la mañana para recap donde estamos que es lo último que falta e idealmente deploy hoy mismo.

La idea sería hacer el meeting abierto para que puedan join los que quieran. 

Agenda
- Demo del app (screen share) cómo está ahora y confirmar que tenemos feature parity con el current app
- Definir pasos finales para poder poner en prod
- Establecer fecha y hora de push a prod

Propongo 10am AST

@jpadilla @froi @miguelrios @albertico 

---

### Meeting details

Topic: Status Meeting v1 - Suministros Puerto Rico
Time: Jan 15, 2020 10:00 AM Puerto Rico

Join Zoom Meeting
https://zoom.us/j/983829701

Meeting ID: 983 829 701

One tap mobile
+17879667727,,983829701# Puerto Rico
+17879451488,,983829701# Puerto Rico

Dial by your location
        +1 787 966 7727 Puerto Rico
        +1 787 945 1488 Puerto Rico
        +1 646 558 8656 US (New York)
        +1 408 638 0968 US (San Jose)
Meeting ID: 983 829 701
Find your local number: https://zoom.us/u/aeC9EdhDSU

**Comment by Xiomara7** [comment]
Attendees: @jpadilla, @gcollazo, @froi, Orlando Vélez, Javier Vélez

**Notes:** 
- Han sugerido hacer un reporte pero debe hacerse manual. 
- @jpadilla  y @gcollazo  van a sync up para hacer deploy y luego seguir v2. 

**Issues discutidos / encontrados durante el call:** 
- [x] https://github.com/Code4PuertoRico/suministrospr/issues/56
- [x] https://github.com/Code4PuertoRico/suministrospr/issues/57
- [x] https://github.com/Code4PuertoRico/suministrospr/issues/58
- [x] https://github.com/Code4PuertoRico/suministrospr/issues/59
- [x] https://github.com/Code4PuertoRico/suministrospr/issues/60
- [x] https://github.com/Code4PuertoRico/suministrospr/issues/61
- [x] https://github.com/Code4PuertoRico/suministrospr/issues/62
- [ ] Tener un twitter para canalizar requests. 
- [ ] Añadir todos los municipios en el dropdown para evitar que se inserten errores.

**Comment by froi** [comment]
@Xiomara7 Gracias por estas notas!!!!

**Comment by miguelrios** [comment]
I missed this. My bad.
