### ISSUE TITLE
Traducir UI

### ISSUE THREAD

**Issue by gcollazo** [Code4PuertoRico/suministrospr#55]
Request: https://mobile.twitter.com/cosmicglimmer/status/1217422947394162689

**Comment by gcollazo** [comment]
https://mobile.twitter.com/oajvelez/status/1217429927974395905

**Comment by ajRiverav** [comment]
i'll take it. OK if it is done tomorrow, though?

**Comment by ajRiverav** [comment]
also, I can look around and check what should be translated, but if you can provide some guiding info, I could have it done in less time.

**Comment by Johnny939** [comment]
Let me know if I can help. 
I found your page on Endi.com yesterday; good job everyone on the website.

**Comment by froi** [comment]
Marking as stale. This issue should be closed by PR #122

**Comment by froi** [comment]
PR #122 has been merged. Closing this issue.
