### ISSUE TITLE
Create edit page

### ISSUE THREAD

**Issue by jpadilla** [Code4PuertoRico/suministrospr#6]
Based on: https://suministrospr.com/helpie_editor_page/?post_id=120

**Comment by froi** [comment]
Edit page seems done. @Code4PuertoRico/suministrospr can we close this?

![image](https://user-images.githubusercontent.com/1918027/72319872-be999b00-3676-11ea-88c5-e5fc9d8e87be.png)

**Comment by froi** [comment]
Editing entry:
<img width="1258" alt="suministros-edit-with-added-text" src="https://user-images.githubusercontent.com/1918027/72320139-6f079f00-3677-11ea-8436-c4ff2f787afe.png">

Validating edit shows up in details:
<img width="1258" alt="suministrospr-detail-with-edit" src="https://user-images.githubusercontent.com/1918027/72320143-7169f900-3677-11ea-92cd-420160c682eb.png">
