### ISSUE TITLE
Crear manera de informar errores

### ISSUE THREAD

**Issue by froi** [Code4PuertoRico/suministrospr#63]
Los usuarios deberían tener una manera de informar errores o ediciones "nefastas" dentro de la misma pagina. Esto permite a los dueños del site corregir las entradas usando la historia que se esta guardando

**Comment by vacas** [comment]
@froi, ¿Qué tenían en mente para registrar estos errores? ¿Enviar un email/slack notification a los admins, registrarlo en el db u otra cosa?

**Comment by froi** [comment]
Creo que registrar en la DB seria bueno. Un especie de flag que indique que esta en review o algo parecido.

Las integraciones con Slack y/o email va a depender de los dueños del site. Si ellos quieren manejar eso entonces seria algo que podemos considerar.

**Comment by vacas** [comment]
Creo que si hay un flag en el db, deberíamos incluir también un text box donde puedan explicar qué está mal o erróneo de la data, ¿no?

No sé si también un campo para obtener el email de la persona que someta el error sería bueno para que se puedan comunicar con esta persona en cualquier caso que falte alguna info adicional, but that'd up to the admins... We could just make that field optional en el peores de los casos.

**Comment by froi** [comment]
All good points. @gcollazo thoughts?

**Comment by vacas** [comment]
Hey, guys. Any updates on this issue? Supongo que habrán otras cosas con más prioridad, so me avisan cuando estén listo con esto o si necesitan ayuda con algún otro ticket.

**Comment by froi** [comment]
@vacas No updates on this.

En los ultimo 26 días las prioridades fueron cambiando y este feature no era una de ellas.

@gcollazo que crees que se deba de hacer con este issue?

**Comment by vacas** [comment]
@froi, that's cool, my friend; Aprecio el aviso.  @gcollazo, me avisas cualquier cosa, aquí a las órdenes 🤟
