### ISSUE TITLE
Aceptar pagos por ATHM, PayPal, etc.

### ISSUE THREAD

**Issue by gcollazo** [Code4PuertoRico/suministrospr#64]
https://mobile.twitter.com/mayoketchuup/status/1217457902438572033

**Comment by miguelrios** [comment]
Paypal es bien fácil si el end-user tiene ya una cuenta. Necesitas su email o su paypal.me link. https://github.com/Code4PuertoRico/prneeds.cash/blob/master/src/components/Paypal/Paypal.js#L17 

Como casi todo el mundo tiene ATH, otro approach puede ser permitir donaciones a "suministrospr" (sponsored by a non profit for tax deductions if possible) taggeadas a un refugio y entonces "suministrospr" enviar el dinero por ATH movil al necesitado. Ahí hay issues de governanza e independencia pero creo q un proxy así sería bien útil ahora mismo.

**Comment by rnegron** [comment]
Me gustaría trabajar en la integración de ATHM por lo menos... Se me ocurre que tal vez haga falta un reusable `django-athm` _a la_ `django-stripe`... Pero no me queda claro cual sería el approach? Un nuevo UI para organizaciones y que se les pueda donar a través del site?

**Comment by gcollazo** [comment]
Me preocupa la idea de ser quienes reciben dinero. Como primero paso sugiero simplemente tener un formulario para que entidad que están aceptando donaciones via uno de estos medios se registren y sean aprobados luego de validación manual de un administrador.

Hay que tener cuidado con el fraude que este tipo de approach facilita.

**Comment by froi** [comment]
Closing as stale. Please reopen if it's going to be worked on.
