### ISSUE TITLE
Añadir assets editables de diseño al repo

### ISSUE THREAD

**Issue by gcollazo** [Code4PuertoRico/suministrospr#69]
¿Hay alguna objeción en añadir los assets editables de diseño al repo? Si no la hay ¿tienes sugerencias de como llamar el directorio para estos assets?

ping @froi @jpadilla

**Comment by froi** [comment]
No tengo objeción. Quizas llamar el directorio `raw_assets`?

**Comment by gcollazo** [comment]
@froi despúes de pensarlo mas de lo que debería me fui con `design` 🤷‍♂
