### ISSUE TITLE
¿Hace falta pautar en Facebook para incrementar visitas de donantes o líderes comunitarios?

### ISSUE THREAD

**Issue by juarbem** [Code4PuertoRico/suministrospr#73]
Wepa, hola, acá desde la Florida me enteré que Giovanni está colaborando con el grupo para organizar la ayuda y me motivé a ver cómo puedo ayudarles. Tengo background en web dev y mercadeo digital, so si surge algo que entiendan que pueda ayudarles, me avisan. 

Se me ocurre que quizás haga falta una manera de llegarle a más líderes de comunidad (targeting páginas de Facebook creadas para recolectas por ejemplo) ó generar más tráfico calificado de donantes en la isla (targeting más amplio). 

Acá unas ideas para ads en FB/Instagram, pero necesitaríamos una página de Facebook. Primero evaluaría si es una táctica que haga falta. De igual forma, si es coders or $ lo que necesitan, también se puede hacer una campaña para esos objetivos.. 

![Screen Shot 2020-01-15 at 11 03 06 AM](https://user-images.githubusercontent.com/59926823/72450001-9b124580-3787-11ea-90a3-732cd2dd9016.png)

![Screen Shot 2020-01-15 at 11 09 36 AM](https://user-images.githubusercontent.com/59926823/72450054-ae251580-3787-11ea-9449-10bed74ba4dc.png)

**Comment by jpadilla** [comment]
@juarbem 👋este repositorio es público. tomé la libertad de entrar a gmail y a twitter para cambiar los passwords, antes que otra persona lo hiciera. Te escribí por el Slack de Startups of Puerto Rico para que continuemos allá.

**Comment by froi** [comment]
Closing this issue as stale.
