### ISSUE TITLE
QA Diseño

### ISSUE THREAD

**Issue by gcollazo** [Code4PuertoRico/suministrospr#77]
- el copy aguante aún más pequeño. 
- font Montserrat.
- el título del Municipio/Sector/Refugio está muy grande still. yo tengo ahora mismo ese título en 35px (montserrat)
- cuadremos los bullets con el párrafo de arriba

**Comment by luisgthb** [comment]
I can take this one.

**Comment by gcollazo** [comment]
@luisv5z do it!

**Comment by gcollazo** [comment]
Hablé con @luisv5z y decidimos movernos away de tailwind y crear CSS custom para los estilos del site. El site es pequeño y como no estamos usando un client side framework, es complicado centralizar y compartir los estilos.

@luisv5z please link este issue a tu PR.

**Comment by froi** [comment]
@gcollazo This seems to be resolved in PR #118. Can we close this issue?

**Comment by luisgthb** [comment]
@froi Was watching your stream and noticed a couple of issues but they can be dealt with separately.
