### ISSUE TITLE
Extract data for migration

### ISSUE THREAD

**Issue by jpadilla** [Code4PuertoRico/suministrospr#8]

**Comment by froi** [comment]
@albertico [completed the scrapper](https://github.com/Code4PuertoRico/suministrospr-web-scraper). Issues should be linked to the scrapper repo and create over there.

Here's the data extract: [suministrospr-raw-data-20190113-2047.zip](https://github.com/Code4PuertoRico/suministrospr/files/4057151/suministrospr-raw-data-20190113-2047.zip)

CC: @jpadilla @miguelrios ☝️
