### ISSUE TITLE
Optimize Suministro “group by”

### ISSUE THREAD

**Issue by arielo** [Code4PuertoRico/suministrospr#84]
The way `suministró` records are fetched could be problematic as the amount of records grow. The `group by` could be done at a DB query level reducing operations and memory usage. 

https://github.com/Code4PuertoRico/suministrospr/blob/a0f6a70cc2f8894dd79a41a43e67f35d851e51ea/suministrospr/suministros/views.py#L26

@gcollazo This is not a blocker for v1 just something to keep an eye out for.

**Comment by rnegron** [comment]
I can take this task.

**Comment by jpadilla** [comment]
Gracias @arielo @rnegron 🎉
