### ISSUE TITLE
Duplicated "sectores"

### ISSUE THREAD

**Issue by miguelrios** [Code4PuertoRico/suministrospr#90]
Hay dupe records. E.g. https://suministrospr.com/sectores/brisas-del-caribe/ and https://suministrospr.com/sectores/1697/ both link to the sector "brisas del caribe".

**Comment by gcollazo** [comment]
Acabo de hablar con @jwvelez y está trabajando en limpiar los datos desde el admin.

**Comment by jwvelez** [comment]
Ya limpié los duplicados. Pude merge algunos, etc. Si se me quedó alguno, me dejan saber. Esto será bastante on-going.

**Comment by gcollazo** [comment]
Closing, cuando aparezcan mas duplicados creamos uno nuevo
