### ISSUE TITLE
Categorización de pedidos

### ISSUE THREAD

**Issue by miguelrios** [Code4PuertoRico/suministrospr#93]
De @mariolapr en Twitter (pediatra usando el site): “Para hacerlo más fácil, opción de buscar por artículo. Por ejemplo digamos que en total, entre todos los campamentos se necesitan 10 glucometros. Con ese número puedo lograr conseguir donaciones de medical supplies.”

**Comment by miguelrios** [comment]
Related to #51. I started a spreadsheet to label some of the asks to see if we can do a simple model that categorize all asks: https://docs.google.com/spreadsheets/d/16alvWnwEu-aMD5IHiUH_NHkuNfB9oaKiWTiGMXp-jSM. Let’s channel brainstorming and progress here. @Xiomara7

**Comment by Xiomara7** [comment]
@miguelrios, ¿para empezar pudiéramos añadir los labels más básicos al form, que la gente misma los vaya categorizando?

**Comment by gcollazo** [comment]
@Xiomara7 por ahí creo que va la cosa... un feature de tags en cada sector y posteriormente un view para filtrar por tags

**Comment by torlanco** [comment]
> @miguelrios, ¿para empezar pudiéramos añadir los labels más básicos al form, que la gente misma los vaya categorizando?

Si, he estado pensando en los labels también. Quizás romper el mas amplio `need_supplies` y usar más específicos: 
# needs
- need_food
- need_water
- need_psycologist
- need_fun
- need_leaders
- need_help_with_elderly
- need_help_with_infants
- need_toys
- need_power
- need_otc_drugs
- need_rx_drugs

# type
- request
- offer

**Comment by torlanco** [comment]
añado:
- need_hygiene
- need_pet_support

need hygiene lo he visto mucho
need_hygiene (!)

**Comment by torlanco** [comment]
necesito un buen label para "Necesitamos catres" ya que ocurre mucho. Ya empece a label btw.
