### ISSUE TITLE
Anñadir un entry "global" a los 78 municipios para mascotas

### ISSUE THREAD

**Issue by oajota** [Code4PuertoRico/suministrospr#94]
Team:

Se comunicaron con nosotros a solicitarnos ayuda con el asunto de muchas mascotas cuyos dueños las dejaron solos en sus casas. Hay grupos listos para recogerlos pero necesitan que los locales que los ven identifiquen donde están en alguna parte y por eso recurrieron a nosotros. 

Mi idea es añadir en las opciones de lugares a los municipios una "global": que se llame "reporta mascotas" y que sea el mismo proceso el usuario entre ponga la info de la mascota y donde se encuentra. 

Les copio aquí la comunicación entera. Me dejan saber cómo proceder. 

¡Saludos Orlando!
 
¡Muchas gracias por tu tiempo! Conforme a nuestra conversación telefónica, abajo le detalla nuestra petición para añadir un área para recoger información sobre mascotas abandonadas debido a los acontecimientos del área sur.  Mi nombre es Viviana Rivera, animal lover comprometida con el bienestar animal en Puerto Rico.  Como parte de un esfuerzo concertado entre diversas organizaciones y personas, estamos queriendo identificar mascotas abandonadas en sus casas debido a los temblores en el área sur de la isla.  Necesitamos colectar y tabular información en un solo lugar que nos permita llegar a ellas.  Lo necesitaríamos en una tipo de forma de contacto que se llena.  Así podremos saber a quien contactar sobre dicha mascota/s.  Info que vamos a necesitar:
 
Municipio/ Pueblo
Zona/Sector
Nombre de Contacto (¿podríamos contactarlo para mas información sobre este animal?)
Numero Telefónico
Correo Electrónico
Especie
Perro
                                                                       i.      Cantidad
Condición
Dentro de estructura comprometida
Suelto en su sector
Usted lo tiene en su hogar temporeramente y lo esta alimentando
¿Es usted rescatista o refugio?
Si / No
                                                                       i.      De ser si,
provéanos información sobre nombre de organización y censo de perros.
Su matricula de perros esta vacunada?
Desea que se considere un vuelo humanitario para su población?
Tiene los records de sus rescates al día?
Tiene alimento para sus rescates?
Esterilizados? Cuantos?
 
Por el momento, entiendo que esta es la información mas importante que necesitamos canalizar ya que al momento hay disponibles unas 1,000 vacunas donadas por un veterinario local así como gestiones para vuelos humanitarios, y movilizaciones siendo concertados por organizaciones de bienestar animal.
 
Quedo a su disposición para cualquier pregunta adicional.
 
Mil gracias,
 
 
 
 
Viviana Rivera
Chief Doggie Officer- Certified Pet Designer
 
signature_1097806984
                          Made for Dogs.  Designed for Owners.
 
m                   787.630.6066
p                     787.957.6307
w                    www.toydoggiebrand.com
 
P.O. Box 897, San Lorenzo, Puerto Rico 00754
signature_1629359839signature_1140204969signature_206585971 
CONFIDENTIALITY NOTICE -- This email is intended only for the person(s) named in the message header. Unless otherwise indicated, it contains information that is confidential, privileged and/or exempt from disclosure under applicable law. If you have received this message in error, please notify the sender of the error and delete the message. Thank you.
This message (including any attachments) may contain confidential, proprietary, privileged and/or private information. The information is intended to be for the use of the individual or entity designated above. If you are not the intended recipient of this message, please notify the sender immediately, and delete the message and any attachments. Any disclosure, reproduction, distribution or other use of this message or any attachments by an individual or entity other than the intended recipient is prohibited.

**Comment by gcollazo** [comment]
@oajota Esto debe ser prácticamente gratis una vez no movamos a solicitar datos más estructurados que es la solución para muchos features que se han solicitado. Organizar los datos de forma estructurada nos da la posibilidad de filtrar y hacer visualizaciones y reportes por cosas específicas como es el caso de los animales.

Esto va en camino. Voy a crear un issue con los detalles y el diseño de la implementación para que podamos keep track. 💪

**Comment by gcollazo** [comment]
Por otro lado el hack que sugieres me parece aceptable por ahora para cubrir la necesidad de forma inmediata. También voy a crear un issue para eso.

**Comment by torlanco** [comment]
Están surgiendo muchos needs especiales como este y #93. Creo que se debe robustecer el feature real que es #51 con el labeling system que propone @miguelrios.

**Comment by gcollazo** [comment]
@torlanco voy a documentar el feature, pero hay una tarea de importación/categorización que es lo que @miguelrios está haciendo. Miguel nos podrá decir si necesita ayuda con eso para convocar más gente.

**Comment by gcollazo** [comment]
Ya tenemos en producción el feature de añadir tags a los posts. Por el momento solo se puede hacer desde el "admin". Esto debe ayudarnos a empezar a categorizar cosas.

**Comment by gcollazo** [comment]
Cerrando pq ya tenemos un issue con el feature que resuelve esto
