### ISSUE TITLE
Filtrar sectores por tags

### ISSUE THREAD

**Issue by gcollazo** [Code4PuertoRico/suministrospr#97]

**Comment by froi** [comment]
Assigned to myself but if anybody wants to work on it just comment here and mention me.

**Comment by ajRiverav** [comment]
what kind of tagging is being considered here? (e.g. item categories, etc..) 

...coming up with ideas that may integrate with #108 while keeping the usability high.

**Comment by jpadilla** [comment]
@froi I can pick this up if you haven't already.

**Comment by froi** [comment]
I haven’t gotten far. Go for it @jpadilla

**Comment by jpadilla** [comment]
idea by @gcollazo 

![home](https://user-images.githubusercontent.com/83319/72668464-36f4b900-39f5-11ea-8565-31d262344e30.png)

![srp](https://user-images.githubusercontent.com/83319/72668463-36f4b900-39f5-11ea-97fe-9f1b40e37f16.png)
