### ISSUE TITLE
clean up a bit user-facing text used across website

### ISSUE THREAD

**Issue by ajRiverav** [Code4PuertoRico/suministrospr#99]
Issue: During my translation (per #55, which I am working on), I noticed the website needs just a little cleaning up of the user-facing text. 

If OK, I can propose the changes via a pull request. THEN, the translation can be done appropriately. 

Example of clean-up need: 
"[...] Esta página pretende ser un vehículo de distribución equitativa para estos suministros, administrada por la misma gente que dona, y que recibe. Para que la ayuda no falte donde se necesita, ni sobre donde ya la tengan."

**Comment by gcollazo** [comment]
@oajota necesitamos tu input aquí

**Comment by oajota** [comment]
@ajRiverav feel free to propose changes or suggest any new information to be added

**Comment by gcollazo** [comment]
@ajRiverav PR separado plis

**Comment by ajRiverav** [comment]
ok;
may want to remove the tag now.

**Comment by gcollazo** [comment]
Closed  by PR #110
